version: '3.8'

services:
  processor:
    build: .
    extra_hosts:
     - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
